### ISSUE TITLE
Results about occlusion edge detection 

### ISSUE THREAD

**Issue by tim885** [buptlr/OFNet#1]
Hi, 
Thanks for releasing your code! By the way, whether can you kindly offer results concerning about occlusion edge detection on PIOD/BSDS? For DOOBNet repo, they also offered this score. 
Thanks by advance!

**Comment by buptlr** [comment]
Hi,
The results can be obtained by running the testing script directly through the models we have uploaded. We will offer the occlusion edge detection results soon.
Best

**Comment by buptlr** [comment]
The results have been updated. Good luck.
