### ISSUE TITLE
learning schedule

### ISSUE THREAD

**Issue by tim885** [buptlr/OFNet#3]
Hi, 
Can you kindly offer the solver_ofnet_bsdsownership.prototxt? With my pytorch-implementation, I reproduced your AP scores but always get 3% drop on ODS and OIS which is quite annoying. Thank you very much!

**Comment by buptlr** [comment]
Hi,
Here is the solver.
`net: "train_val_ofnet_bsdsownership.prototxt"
test_iter: 0
test_interval: 1000000
# lr for fine-tuning should be lower than when starting from scratch
# debug_info: true
base_lr: 0.00003
lr_policy: "step"
gamma: 0.1
# iterate for a larger batch 
# clip_gradients:100000
iter_size: 1
# stepsize should also be lower, as we're closer to being done 
stepsize: 4000
display: 20
max_iter: 10000
momentum: 0.9
weight_decay: 0.0002
snapshot: 2000
snapshot_prefix: "../snapshots/ofnet_bsdsownership"
# uncomment the following to default to CPU mode solving
# solver_mode: CPU 
`
Best

**Comment by buptlr** [comment]
Hi,
Here is the solver_ofnet_bsdsownership.prototxt.
```
net: "train_val_ofnet_bsdsownership.prototxt"
test_iter: 0
test_interval: 1000000
# lr for fine-tuning should be lower than when starting from scratch
# debug_info: true
base_lr: 0.00003
lr_policy: "step"
gamma: 0.1
# iterate for a larger batch 
# clip_gradients:100000
iter_size: 1
# stepsize should also be lower, as we're closer to being done 
stepsize: 4000
display: 20
max_iter: 10000
momentum: 0.9
weight_decay: 0.0002
snapshot: 2000
snapshot_prefix: "../snapshots/ofnet_bsdsownership"
# uncomment the following to default to CPU mode solving
# solver_mode: CPU 
```
Best
